CREATE TABLE IF NOT EXISTS tenants (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_key VARCHAR(64) NOT NULL,
  display_name VARCHAR(190) NOT NULL,
  vkn_tckn VARCHAR(11) NOT NULL,
  address VARCHAR(500) NOT NULL,
  integrator_driver VARCHAR(20) NOT NULL DEFAULT 'nilvera',
  integrator_credentials TEXT NOT NULL,
  api_key_hash CHAR(64) NOT NULL,
  allowed_ips VARCHAR(500) NULL,
  webhook_url VARCHAR(500) NULL,
  webhook_secret TEXT NOT NULL,
  tax_profile JSON NOT NULL,
  mode VARCHAR(10) NOT NULL DEFAULT 'test',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY tenants_tenant_key_unique (tenant_key),
  UNIQUE KEY tenants_api_key_hash_unique (api_key_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  type VARCHAR(10) NOT NULL DEFAULT 'earsiv',
  external_id VARCHAR(190) NULL,
  ettn CHAR(36) NULL,
  invoice_number VARCHAR(32) NULL,
  currency CHAR(3) NOT NULL DEFAULT 'TRY',
  exchange_rate DECIMAL(15,6) NULL,
  total DECIMAL(15,2) NOT NULL,
  tax_total DECIMAL(15,2) NOT NULL,
  request_payload JSON NOT NULL,
  response_payload JSON NULL,
  error_message TEXT NULL,
  attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
  pdf_path VARCHAR(500) NULL,
  sent_at DATETIME(3) NULL,
  cancelled_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY invoices_tenant_id_idempotency_key_unique (tenant_id, idempotency_key),
  KEY invoices_tenant_id_status_idx (tenant_id, status),
  KEY invoices_external_id_idx (external_id),
  CONSTRAINT invoices_tenant_id_fk FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoice_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice_id BIGINT UNSIGNED NOT NULL,
  from_status VARCHAR(20) NULL,
  to_status VARCHAR(20) NOT NULL,
  actor VARCHAR(40) NOT NULL,
  reason VARCHAR(500) NULL,
  meta JSON NULL,
  created_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  KEY invoice_events_invoice_id_created_at_idx (invoice_id, created_at),
  CONSTRAINT invoice_events_invoice_id_fk FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
